Retrieve paintings by artist name
lucasdavid/wikiart pull request #22
Opened 2022-08-29 09:51 UTC by lparth

This patch enables retrieving paintings by any portion of an artist
name. Multiple artists' paintings can be retrieved if names match.

2022-08-29 11:16 UTC, lparth commented
Also posted a demo video of this feature:

https://www.youtube.com/watch?v=KG0YvvAKf6A

If you need updates/modifications on this patch let me know, and thank you for writing this useful tool.

~parthi

2022-08-29 21:59 UTC, lucasdavid commented on wikiart/console.py
> +                             choices=('artists', 'paintings', 'all', 'artist'),
Remove `artist` here.

2022-08-29 22:12 UTC, lucasdavid commented
Thank you very much for the contribution. Just a few considerations before merging.

2022-08-30 09:30 UTC, lparth commented
Sure, please let me know your comments and I'll make the changes. Thank you.

2022-08-30 09:35 UTC, lparth commented
I dropped the commit that had a demo video link from the PR. It was temporarily added for a presentation. It's not needed for the documentation.

2022-08-30 14:00 UTC, lucasdavid requested changes

2022-08-30 14:00 UTC, lucasdavid commented on wikiart/console.py
> +                             choices=('artists', 'paintings', 'all', 'artist'),
Remove artist from here.

2022-08-30 14:00 UTC, lucasdavid commented on wikiart/fetcher.py
> +    def fetch_artist(self, artistName):
`artist_name`

2022-08-30 14:00 UTC, lucasdavid commented on wikiart/fetcher.py
> +            raise RuntimeError('Artist Not found. Cannot continue.')
I believe `Logger.error('...')` is better than raising an error in these two, as many people without computer science background use this tool and don't really understand/find stack traces useful.

2022-08-30 14:00 UTC, lucasdavid commented on wikiart/console.py
> +        p_fetch.add_argument('--artistname', type=str, required=False)
I think you could merge this parameter with `--only` (by removing choices from only and letting users do `python wikiart.sh --only gogh`).

2022-08-30 14:00 UTC, lucasdavid commented on wikiart/console.py
> +            if args.only == 'artist':
```py
if args.only == 'paintings':
  f.fetch_all_paintings()
elif args.only != 'artists':
  # Looking for a specific painter.
  f.fetch_artist(args.only).copy_everything()
```

2022-08-30 14:08 UTC, lparth commented on wikiart/console.py
> +        p_fetch.add_argument('--artistname', type=str, required=False)
Cool, I'll do that update the PR. Cheers.

2022-08-30 15:05 UTC, lparth commented
Thanks for the comments and code. I've pushed (squashed into a single commit) the changes. I think raising an error is better when chaining functions, so I raise ValueError and handle it at the console and dump it to the logger to give a user-friendly experience. Let me know what you think. 

Cheers,
~parthi

2022-08-30 19:11 UTC, lucasdavid commented
Great. Thank you once again.

2022-08-30 19:11 UTC, merged

2022-08-30 19:43 UTC, lparth commented
That's great. Thanks
~parthi

On Tue, 30 Aug 2022, 20:11 Lucas David, ***@***.***> wrote:

> Great. Thank you once again.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lucasdavid/wikiart/pull/22#issuecomment-1232060229>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABQ5ZGPE4RDRKFIOHANEGLV3ZMFRANCNFSM575EHQ5A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>